# Generated by Django 4.2.11 on 2024-05-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('faqbody', models.CharField(max_length=1000)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
