# Generated by Django 4.2.11 on 2024-06-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='acc_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='remail',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
